"use client";

import React from "react";
import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  ArrowRight,
  BadgeCheck,
  Bell,
  Building2,
  CalendarDays,
  ChartColumnBig,
  ChartNoAxesCombined,
  CheckCheck,
  CheckCircle2,
  ChevronRight,
  CircleHelp,
  Cloud,
  ClipboardCheck,
  Clock3,
  Eye,
  EyeOff,
  Download,
  Factory,
  FileText,
  FolderX,
  Gavel,
  Gift,
  GraduationCap,
  HandHeart,
  Landmark,
  LayoutDashboard,
  Leaf,
  ListOrdered,
  Lock,
  LogOut,
  Mail,
  Medal,
  Paperclip,
  Plus,
  Rocket,
  Settings,
  ShieldUser,
  Sparkles,
  Target,
  Trophy,
  TriangleAlert,
  UserPlus,
  Users,
  UsersRound,
  X,
} from "lucide-react";
import type { LucideProps } from "lucide-react";

const iconMap = {
  add: Plus,
  admin_panel_settings: ShieldUser,
  analytics: ChartNoAxesCombined,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  assessment: FileText,
  attachment: Paperclip,
  badge: BadgeCheck,
  badges: Medal,
  bell: Bell,
  account_balance: Landmark,
  calendar_today: CalendarDays,
  carbon: Cloud,
  check_circle: CheckCircle2,
  chevron_right: ChevronRight,
  co2: Cloud,
  close: X,
  dashboard: LayoutDashboard,
  description: FileText,
  diversity_3: UsersRound,
  done_all: CheckCheck,
  download: Download,
  eco: Leaf,
  emoji_events: Trophy,
  factory: Factory,
  fact_check: ClipboardCheck,
  gavel: Gavel,
  group: Users,
  folder_off: FolderX,
  leaderboard: ListOrdered,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  military_tech: Medal,
  notifications: Bell,
  person_add: UserPlus,
  progress_activity: Activity,
  picture_as_pdf: FileText,
  redeem: Gift,
  rocket_launch: Rocket,
  schedule: Clock3,
  school: GraduationCap,
  settings: Settings,
  shield_person: ShieldUser,
  stars: Sparkles,
  task_alt: BadgeCheck,
  tune: Settings,
  track_changes: Target,
  trending_down: TriangleAlert,
  trending_up: ArrowUp,
  volunteer_activism: HandHeart,
  warning: AlertTriangle,
  verified: BadgeCheck,
  visibility: Eye,
  visibility_off: EyeOff,
} as const;

export type AppIconName = keyof typeof iconMap;

interface AppIconProps extends Omit<LucideProps, "ref"> {
  name: AppIconName | string;
}

export default function AppIcon({ name, className, size = "1em", strokeWidth = 1.8, ...props }: AppIconProps) {
  const Icon = iconMap[name as AppIconName] ?? CircleHelp;

  return <Icon className={className} size={size} strokeWidth={strokeWidth} aria-hidden="true" {...props} />;
}